name: Terraform pipeline

on:
  push:
    branches:
      - main

env:
  TERRAFORM_VERSION: "1.8.1"
  TF_ROOT: project
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}


jobs:
  plan:
    name: Terraform plan
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: terraform init
        working-directory: ${{ env.TF_ROOT }}
        shell: bash
        run: |
          terraform init

      - name: terraform plan
        working-directory: ${{ env.TF_ROOT }}
        shell: bash
        run: |
          terraform plan